export const parts: Record<number, string> = {
    // 0: "Kills",
    // 1: "Ubers",
    2: "Kill Assists",
    // 3: "Sentry Kills",
    // 4: "Sodden Victims",
    // 5: "Spies Shocked",
    6: "Heads Taken",
    7: "Humiliations",
    // 8: "Gifts Given",
    // 9: "Deaths Feigned",
    10: "Scouts Killed",
    11: "Snipers Killed",
    12: "Soldiers Killed",
    13: "Demomen Killed",
    14: "Heavies Killed",
    15: "Pyros Killed",
    16: "Spies Killed",
    17: "Engineers Killed",
    18: "Medics Killed",
    19: "Buildings Destroyed",
    20: "Projectiles Reflected",
    21: "Headshot Kills",
    22: "Airborne Enemy Kills",
    23: "Gib Kills",
    // 24: "Buildings Sapped",
    // 25: "Tickle Fights Won",
    // 26: "Opponents Flattened",
    27: "Kills Under A Full Moon",
    28: "Dominations",
    30: "Revenges",
    31: "Posthumous Kills",
    32: "Teammates Extinguished",
    33: "Critical Kills",
    34: "Kills While Explosive-Jumping",
    36: "Sappers Destroyed" /*"Sappers Removed"*/,
    37: "Cloaked Spies Killed",
    38: "Medics Killed That Have Full ÜberCharge",
    39: "Robots Destroyed",
    40: "Giant Robots Destroyed",
    44: "Kills While Low Health",
    45: "Kills During Halloween",
    46: "Robots Killed During Halloween",
    47: "Defender Kills",
    48: "Submerged Enemy Kills",
    // 49: "Kills While Invuln ÜberCharged",
    // 50: "Food Items Eaten",
    // 51: "Banners Deployed",
    // 58: "Seconds Cloaked",
    // 59: "Health Dispensed to Teammates",
    // 60: "Teammates Teleported",
    61: "Tanks Destroyed",
    62: "Long-Distance Kills",
    // 63: "KillEaterEvent_UniquePlayerKills",
    // 64: "Points Scored",
    // 65: "Double Donks",
    // 66: "Teammates Whipped",
    67: "Kills during Victory Time",
    68: "Robot Scouts Destroyed",
    74: "Robot Spies Destroyed",
    77: "Taunt Kills",
    78: "Unusual-Wearing Player Kills",
    79: "Burning Player Kills",
    80: "Killstreaks Ended",
    81: "Freezecam Taunt Appearances",
    82: "Damage Dealt",
    83: "Fires Survived",
    84: "Allied Healing Done",
    85: "Point Blank Kills",
    // 86: "Wrangled Sentry Kills",
    87: "Kills",
    88: "Full Health Kills",
    89: "Taunting Player Kills",
    /*
    90: "Carnival Kills",
    91: "Carnival Underworld Kills",
    92: "Carnival Games Won",
    */
    93: "Not Crit nor MiniCrit Kills",
    94: "Players Hit" /* "Player Hits" */,
    95: "Assists",
    //96: "Contracts Completed",
    97: "Kills",
    /* 98: "Contract Points",
    99: "Contract Bonus Points",
    100: "Times Performed",
    101: "Kills and Assists during Invasion Event",
    102: "Kills and Assists on 2Fort Invasion",
    103: "Kills and Assists on Probed",
    104: "Kills and Assists on Byre",
    105: "Kills and Assists on Watergate",
    106: "Souls Collected",
    107: "Merasmissions Completed",
    108: "Halloween Transmutes Performed",
    109: "Power Up Canteens Used",
    110: "Contract Points Earned",
    111: "Contract Points Contributed To Friends",*/
}; 
